name: test.yml
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.2'

      - name: Run tests
        run: go test -v ./...
