name: Run tests
on:
  push:
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.2'

      - name: Build
        run: go test -c github.com/linuxfight/yandexCalcApi/pkg/calc -o calc-test

      - name: Run tests
        run: ./calc-test -test.paniconexit0
